services:
  db:
    image: postgres:16.2-alpine3.19
    restart: always
    env_file:
      - '.env'
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: health
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  db-test:
    image: postgres:16.2-alpine3.19
    restart: always
    env_file:
      - '.env'
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: health
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres